### ISSUE TITLE
Secrets for the initContainer

### ISSUE THREAD

**Issue by bjarneo** [gimlet-io/onechart#127]
👋 

Our company has been using this chart for a while, and it works as a charm. However, today we wanted an initContainer to run some migrations before the pods started, and we would need access to secrets we pass as env vars to that container. I noticed there is no such thing while looking at the template.

Can something like this be added? https://github.com/gimlet-io/onechart/blob/96a5c6b810eab90408abb034faa002f6efc25023/charts/static-site/templates/deployment.yaml#L47-L49

I assume the location is here: https://github.com/gimlet-io/onechart/blob/master/charts/common/templates/_podSpec.yaml#L13-L35

I can surely create a PR for this.

Thank you for creating this gem of a chart!

**Comment by bjarneo** [comment]
After creating this issue I noticed this PR which I vote yes for! https://github.com/gimlet-io/onechart/pull/67/files

**Comment by YoucefGuichi** [comment]
Hi @bjarneo! Thank you for using onechart. We have resolved the issue you brought up in our latest release: https://github.com/gimlet-io/onechart/releases/tag/v0.71.0.

Please feel free to share any suggestions or let us know if there is anything else we can improve. I’ll close this issue for now since it's been resolved, but feel free to reopen it if necessary.
